### ISSUE TITLE
Error message after skipping the refining step.

### ISSUE THREAD

**Issue by jamesgspercy** [salvocamiolo/GRACy#3]
Hello,

I'm assisting a user with running GRACy v0.4.4 and am encountering an error: 

"You chose not to run the assembly refining step but the finalScaffold.fasta file is not there. Now exiting......"

Is this to be expected if Refine_assembly has been set to "no" in the assembly.conf? 

The finalScaffold.fasta can be located in the folders:
3_scaffoldsOrientation
4_createConsensus

I'm not a specialist in bioinformatics so I apologize if this question lacks context. I'm happy to provide more info with some guidance.

Thanks.

**Comment by salvocamiolo** [comment]
> 

Hi There,
you are absolutely right. GRACy works by performing each of the steps described in the configuration file. Each module in the assembler takes in input the output of the preceding module. Therefore, I would suggest the user to just say yes to all the steps in the configuration file. In this regard, only the first step can be avoided eventually. This is the read quality filtering. Many people in the field think that the quality filter is not necessary and sometimes non-beneficial necessarily. I am among them and generally do not quality filter the reads when I do the assembly.
I hope this helps

**Comment by jamesgspercy** [comment]
Great, thank you so much. I'll try this out.
